git_repository(
  name = "io_bazel_rules_go",
  remote = "https://github.com/bazelbuild/rules_go.git",
  tag = "0.5.2",
)

load(
  "@io_bazel_rules_go//go:def.bzl",
  "go_repositories",
  "go_repository",
)

go_repositories()

go_repository(
  name = "com_github_golang_glog",
  importpath = "github.com/golang/glog",
  commit = "23def4e6c14b4da8ac2ed8007337bc5eb5007998",
)

go_repository(
  name = "io_k8s_apimachinery",
  importpath = "k8s.io/apimachinery",
  # based on git url from go get -v k8s.io/apimachinery/pkg/api/errors
  commit = "6134cb2da6d90597b0434e349f90f94fafc9ae51"
)

go_repository(
  name = "io_k8s_client-go",
  importpath = "k8s.io/client-go",
  tag = "v3.0.0"
)

git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.7.2",
)

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_repositories")
go_proto_repositories()

http_archive(
    name = "io_kubernetes_build",
    sha256 = "a9fb7027f060b868cdbd235a0de0971b557b9d26f9c89e422feb80f48d8c0e90",
    strip_prefix = "repo-infra-9dedd5f4093884c133ad5ea73695b28338b954ab",
    urls = ["https://github.com/kubernetes/repo-infra/archive/9dedd5f4093884c133ad5ea73695b28338b954ab.tar.gz"],
)

go_repository(
  name = "com_github_google_gofuzz",
  importpath = "github.com/google/gofuzz",
  commit = "24818f796faf91cd76ec7bddd72458fbced7a6c1"
)

go_repository(
  name = "com_github_gogo_protobuf",
  importpath = "github.com/gogo/protobuf",
  commit = "7b6c6391c4ff245962047fc1e2c6e08b1cdfa0e8"
)

# or https://github.com/tnarg/rules_go_swagger ?
go_repository(
  name = "com_github_go_openapi_spec",
  commit = "e51c28f07047ad90caff03f6450908720d337e0c",
  importpath = "github.com/go-openapi/spec",
)
